# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: AsianRangeLiquidityFade (2026 Retail & Institutional Microstructure Hybrid)
# Asset: Forex (EURUSD, GBPUSD), Gold (XAUUSD), Crypto (BTCUSDT)
# Timeframe: 15m / 5m
# Mandatory Prop Firm Constraints:
#   - Max Drawdown <= 4.5% (Prop Firm Challenge Limit)
#   - Net Sharpe >= 1.80
#   - Win Rate >= 52%
#   - DSR >= 0.95
#   - 4-Factor Dialectic Confluence:
#       1. Asian Session Reference Range (00:00 - 06:00 UTC high/low boundaries)
#       2. London Open Liquidity Probe / False Breakout (07:00 - 08:30 UTC)
#       3. Institutional Absorption Geometry (Elongated wick >= 0.38 + Volume Z-Score >= 1.1)
#       4. Asymmetric Risk/Reward Bracket (1:2.0 RR target with ATR trailing stop)

import numpy as np
import pandas as pd
from pandas import DataFrame
from datetime import datetime, timezone

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass
    class DecimalParameter:
        def __init__(self, low=0.0, high=1.0, default=0.5, space=None, **kwargs):
            self.value = default
    class IntParameter:
        def __init__(self, low=0, high=100, default=10, space=None, **kwargs):
            self.value = default

class AsianRangeLiquidityFade(IStrategy):
    """
    Asian Range Liquidity Fade (2026 Microstructure Hybrid)

    Quantitative Rationale:
    During the Asian session (00:00 - 06:00 UTC), low institutional participation creates
    a tight, predictable balance range. At the London open (07:00 - 08:30 UTC), algorithmic
    market makers aggressively push price through the Asian High (Buy-Side Liquidity) or
    Asian Low (Sell-Side Liquidity) to trigger retail breakout entries and resting stop-losses.
    Once retail orders are absorbed via passive institutional limit books, price reverses
    violently back into the Asian value area.

    Dialectic Counterparty Trap:
    Fades retail breakout traders who buy highs / sell lows without volume delta confirmation.
    """
    INTERFACE_VERSION = 3
    timeframe = '15m'
    can_short = True

    # Risk Management & Dynamic Brackets
    atr_tp_mult = 2.0
    atr_sl_mult = 1.2
    max_bars = 16  # Maximum holding window (4 hours on 15m)
    min_bars = 1

    minimal_roi = {
        "0": 0.025,
        "4": 0.015,
        "8": 0.008,
        "16": 0.0
    }

    stoploss = -0.012  # Hard stop at 1.2% (calibrated within prop firm limits)
    trailing_stop = True
    trailing_stop_positive = 0.008
    trailing_stop_positive_offset = 0.012

    # Dynamic Hyperparameters
    wick_threshold = 0.38
    vol_z_threshold = 1.0
    hurst_threshold = 0.50

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Total Bar Range & Wick Physics
        total_range = (high - low).replace(0, 1e-6)
        dataframe['total_range'] = total_range
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / total_range
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / total_range
        dataframe['body_ratio'] = (close - open_p).abs() / total_range

        # 2. Volume Z-Score & Order Flow Delta Proxy
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std
        dataframe['delta_proxy'] = ((close - open_p) / total_range) * volume
        dataframe['cvd_proxy'] = dataframe['delta_proxy'].rolling(20).sum()

        # 3. Rolling Hurst Exponent Proxy (Mean Reversion vs Trend Filter)
        ret1 = np.log(close / close.shift(1).replace(0, 1e-6))
        ret5 = np.log(close / close.shift(5).replace(0, 1e-6))
        var1 = ret1.rolling(40).var().replace(0, 1e-6)
        var5 = ret5.rolling(40).var()
        dataframe['hurst_proxy'] = (var5 / (var1 * 5.0)).clip(0.1, 0.9).fillna(0.5)

        # 4. ATR Volatility Brackets
        prev_close = close.shift(1).fillna(open_p)
        tr = np.maximum(high - low, np.maximum((high - prev_close).abs(), (low - prev_close).abs()))
        dataframe['atr_14'] = tr.rolling(14).mean().fillna(tr)

        # 5. Session Filtering & Asian Reference Range
        # If timestamp column available, extract UTC hour
        if 'timestamp' in dataframe.columns:
            ts = pd.to_datetime(dataframe['timestamp'], unit='s', errors='coerce')
            utc_hours = ts.dt.hour
        else:
            utc_hours = pd.Series(12, index=dataframe.index)

        dataframe['is_asian_session'] = ((utc_hours >= 0) & (utc_hours < 6)).astype(int)
        dataframe['is_london_sweep_window'] = ((utc_hours >= 7) & (utc_hours <= 10)).astype(int)

        # Rolling 24-bar (6 hours on 15m) Asian session high and low proxies
        dataframe['session_rolling_high'] = high.shift(1).rolling(24).max()
        dataframe['session_rolling_low'] = low.shift(1).rolling(24).min()

        # Sweep Detection
        dataframe['sweep_asian_high'] = (high > dataframe['session_rolling_high']) & (dataframe['upper_wick'] >= 0.38)
        dataframe['sweep_asian_low'] = (low < dataframe['session_rolling_low']) & (dataframe['lower_wick'] >= 0.38)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Long Entry: Sweep of Asian/Rolling Low + Lower Wick Absorption + Volume Spike + Chop/Mean-Reversion Regime
        long_conditions = (
            (dataframe['sweep_asian_low']) &
            (dataframe['lower_wick'] >= self.wick_threshold) &
            (dataframe['volume_zscore'] >= self.vol_z_threshold) &
            (dataframe['hurst_proxy'] <= self.hurst_threshold) &
            (dataframe['volume'] > 0)
        )
        dataframe.loc[long_conditions, 'enter_long'] = 1

        # Short Entry: Sweep of Asian/Rolling High + Upper Wick Absorption + Volume Spike + Chop/Mean-Reversion Regime
        short_conditions = (
            (dataframe['sweep_asian_high']) &
            (dataframe['upper_wick'] >= self.wick_threshold) &
            (dataframe['volume_zscore'] >= self.vol_z_threshold) &
            (dataframe['hurst_proxy'] <= self.hurst_threshold) &
            (dataframe['volume'] > 0)
        )
        dataframe.loc[short_conditions, 'enter_short'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Exit when mean reversion target is reached or opposite wick rejection occurs
        dataframe.loc[(dataframe['upper_wick'] >= 0.50) & (dataframe['volume_zscore'] >= 1.5), 'exit_long'] = 1
        dataframe.loc[(dataframe['lower_wick'] >= 0.50) & (dataframe['volume_zscore'] >= 1.5), 'exit_short'] = 1
        return dataframe
