# --- Freqtrade Strategy Generated by NujinAI ---
# Thesis: Multi Scale Trend Ribbon
# Archetype: trend_following
# Target Constraints: Net Sharpe >= 1.80, MaxDD <= 4.5%, DSR >= 0.95

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass
    class DecimalParameter:
        def __init__(self, *args, **kwargs): self.value = kwargs.get('default', 0.0)
    class IntParameter:
        def __init__(self, *args, **kwargs): self.value = kwargs.get('default', 0)

class MultiScaleTrendRibbonStrategy(IStrategy):
    """
    Multi Scale Trend Ribbon
    Archetype: TREND_FOLLOWING
    Autonomous quantitative strategy generated by NujinSkills engine.
    """
    INTERFACE_VERSION = 3
    timeframe = '15m'
    can_short = True

    minimal_roi = {
        "0": 0.06,
        "12": 0.03,
        "24": 0.0
}

    stoploss = -0.02
    trailing_stop = True
    trailing_stop_positive = 0.015
    trailing_stop_positive_offset = 0.024

    # EMA Lookback Spaces
    buy_ema_fast_13 = IntParameter(10, 20, default=13, space='buy')
    buy_ema_mid_34 = IntParameter(25, 45, default=34, space='buy')
    buy_ema_slow = IntParameter(40, 70, default=50, space='buy')
    # RSI Hyperparameter Space
    buy_rsi_threshold = IntParameter(20, 55, default=30, space='buy')
    sell_rsi_threshold = IntParameter(55, 85, default=70, space='sell')
    # ADX Trend Filter Space
    buy_adx_min = IntParameter(15, 35, default=20, space='buy')

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Exponential Moving Averages
        dataframe['ema_13'] = dataframe['close'].ewm(span=13).mean()
        dataframe['ema_34'] = dataframe['close'].ewm(span=34).mean()
        dataframe['ema_50'] = dataframe['close'].ewm(span=50).mean()

        # RSI (14)
        delta_14 = dataframe['close'].diff()
        gain_14 = delta_14.clip(lower=0)
        loss_14 = -delta_14.clip(upper=0)
        avg_gain_14 = gain_14.ewm(span=14).mean()
        avg_loss_14 = loss_14.ewm(span=14).mean().replace(0, 1e-6)
        rs_14 = avg_gain_14 / avg_loss_14
        dataframe['rsi_14'] = 100.0 - (100.0 / (1.0 + rs_14))

        # Average True Range (14)
        prev_close = dataframe['close'].shift(1).fillna(dataframe['open'])
        tr = np.maximum(dataframe['high'] - dataframe['low'],
                        np.maximum((dataframe['high'] - prev_close).abs(), (dataframe['low'] - prev_close).abs()))
        dataframe['atr_14'] = tr.rolling(14).mean().fillna(tr)

        # Directional Movement & ADX (14)
        up_move = dataframe['high'].diff()
        down_move = -dataframe['low'].diff()
        plus_dm = np.where((up_move > down_move) & (up_move > 0), up_move, 0.0)
        minus_dm = np.where((down_move > up_move) & (down_move > 0), down_move, 0.0)
        atr_ref = dataframe.get('atr_14', dataframe.get('atr_14', dataframe['high'] - dataframe['low']))
        plus_di = 100.0 * pd.Series(plus_dm, index=dataframe.index).ewm(span=14).mean() / atr_ref.replace(0, 1e-6)
        minus_di = 100.0 * pd.Series(minus_dm, index=dataframe.index).ewm(span=14).mean() / atr_ref.replace(0, 1e-6)
        dataframe['plus_di'] = plus_di
        dataframe['minus_di'] = minus_di
        dx = 100.0 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0, 1e-6)
        dataframe['adx_14'] = dx.ewm(span=14).mean()
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        try:
            dataframe.loc[dataframe.eval('close > ema_50 and ema_13 > ema_34 and rsi_14 > 45 and adx_14 > 22'), 'enter_long'] = 1
        except Exception as e:
            pass

        if self.can_short:
            try:
                dataframe.loc[dataframe.eval('close < ema_50 and ema_13 < ema_34 and rsi_14 < 55 and adx_14 > 22'), 'enter_short'] = 1
            except Exception as e:
                pass
        else:
            dataframe['enter_short'] = 0

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        try:
            dataframe.loc[dataframe.eval('close < ema_34'), 'exit_long'] = 1
        except Exception:
            pass
        try:
            dataframe.loc[dataframe.eval('close < ema_34'), 'exit_short'] = 1
        except Exception:
            pass
        return dataframe
