# --- Freqtrade Strategy Generated by NujinAI ---
# Thesis: Trend Following EMA ADX Momentum
# Archetype: trend_following
# Target Constraints: Net Sharpe >= 1.80, MaxDD <= 4.5%, DSR >= 0.95

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass

class TrendFollowingEmaAdxMomentumStrategy(IStrategy):
    """
    Trend Following EMA ADX Momentum
    Archetype: TREND_FOLLOWING
    Autonomous quantitative strategy generated by NujinSkills engine.
    """
    INTERFACE_VERSION = 3
    timeframe = '15m'
    can_short = True

    minimal_roi = {
        "0": 0.055,
        "12": 0.0275,
        "24": 0.0
}

    stoploss = -0.02
    trailing_stop = True
    trailing_stop_positive = 0.0138
    trailing_stop_positive_offset = 0.022

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Volume Z-Score
        vol_mean = dataframe['volume'].rolling(20).mean()
        vol_std = dataframe['volume'].rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (dataframe['volume'] - vol_mean) / vol_std

        # Exponential Moving Averages
        dataframe['ema_9'] = dataframe['close'].ewm(span=9).mean()
        dataframe['ema_21'] = dataframe['close'].ewm(span=21).mean()
        dataframe['ema_50'] = dataframe['close'].ewm(span=50).mean()

        # RSI (14)
        delta = dataframe['close'].diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)
        avg_gain = gain.ewm(span=14).mean()
        avg_loss = loss.ewm(span=14).mean().replace(0, 1e-6)
        rs = avg_gain / avg_loss
        dataframe['rsi_14'] = 100.0 - (100.0 / (1.0 + rs))

        # Average True Range (14)
        prev_close = dataframe['close'].shift(1).fillna(dataframe['open'])
        tr = np.maximum(dataframe['high'] - dataframe['low'],
                        np.maximum((dataframe['high'] - prev_close).abs(), (dataframe['low'] - prev_close).abs()))
        dataframe['atr_14'] = tr.rolling(14).mean().fillna(tr)

        # Directional Movement & ADX (14)
        up_move = dataframe['high'].diff()
        down_move = -dataframe['low'].diff()
        plus_dm = np.where((up_move > down_move) & (up_move > 0), up_move, 0.0)
        minus_dm = np.where((down_move > up_move) & (down_move > 0), down_move, 0.0)
        plus_di = 100.0 * pd.Series(plus_dm, index=dataframe.index).ewm(span=14).mean() / dataframe['atr_14'].replace(0, 1e-6)
        minus_di = 100.0 * pd.Series(minus_dm, index=dataframe.index).ewm(span=14).mean() / dataframe['atr_14'].replace(0, 1e-6)
        dataframe['plus_di'] = plus_di
        dataframe['minus_di'] = minus_di
        dx = 100.0 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0, 1e-6)
        dataframe['adx_14'] = dx.ewm(span=14).mean()
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        try:
            dataframe.loc[dataframe.eval('close > ema_50 and ema_9 > ema_21 and adx_14 > 20 and rsi_14 > 50 and volume_zscore > 0.5'), 'enter_long'] = 1
        except Exception as e:
            pass

        if self.can_short:
            try:
                dataframe.loc[dataframe.eval('close < ema_50 and ema_9 < ema_21 and adx_14 > 20 and rsi_14 < 50 and volume_zscore > 0.5'), 'enter_short'] = 1
            except Exception as e:
                pass
        else:
            dataframe['enter_short'] = 0

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        try:
            dataframe.loc[dataframe.eval('close < ema_21'), 'exit_long'] = 1
        except Exception:
            pass
        try:
            dataframe.loc[dataframe.eval('close < ema_21'), 'exit_short'] = 1
        except Exception:
            pass
        return dataframe
