# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: CandlePulseFlipTester (Live Pipeline Diagnostic & Signal Verification Tool)
# Asset: Universal (XAU/USD, BTC/USDT, S&P 500)
# Timeframe: 1m (Fast Intraday Verification)
# Rationale:
#   Diagnostic test strategy designed to verify live order execution, WebSocket telemetry,
#   and UI signal dispatching. Buys immediately after any bullish candle (close > open)
#   and sells immediately after any bearish candle (close < open).

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass
    DecimalParameter = float
    IntParameter = int

class CandlePulseFlipTester(IStrategy):
    """
    Diagnostic Candle Flip Strategy for testing live signal pipeline:
    - Triggers BUY on ANY bullish closed candle (close > open)
    - Triggers SELL on ANY bearish closed candle (close < open)
    - Fast 1-2 bar holding horizon so positions exit and allow immediate new signals.
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = True

    # Risk Management brackets (tight 0.15% to allow rapid exits)
    atr_multiplier = 1.0
    atr_tp_mult = 1.0
    atr_sl_mult = 1.0

    min_bars = 1
    max_bars = 2

    minimal_roi = {
        "0": 0.0015,
        "1": 0.0005,
        "2": 0.0
    }

    stoploss = -0.0015
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']

        # ATR for dynamic SL/TP calculation
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # Bullish / Bearish candle classification
        dataframe['is_bullish'] = (close > open_p).astype(int)
        dataframe['is_bearish'] = (close < open_p).astype(int)

        # Structural brackets for live visual cockpit
        dataframe['structural_sl'] = np.where(
            dataframe['is_bullish'] == 1,
            np.round(close - np.maximum(dataframe['atr_14'], close * 0.0015), 2),
            np.round(close + np.maximum(dataframe['atr_14'], close * 0.0015), 2)
        )
        dataframe['structural_tp'] = np.where(
            dataframe['is_bullish'] == 1,
            np.round(close + np.maximum(dataframe['atr_14'], close * 0.0015), 2),
            np.round(close - np.maximum(dataframe['atr_14'], close * 0.0015), 2)
        )

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['enter_long'] = 0
        dataframe['enter_short'] = 0

        # Flip signals based on current closed bar
        dataframe.loc[dataframe['is_bullish'] == 1, 'enter_long'] = 1
        dataframe.loc[dataframe['is_bearish'] == 1, 'enter_short'] = 1

        # Prevent simultaneous long/short
        both = (dataframe['enter_long'] == 1) & (dataframe['enter_short'] == 1)
        dataframe.loc[both, 'enter_short'] = 0

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0

        # Opposite candle triggers exit
        dataframe.loc[dataframe['is_bearish'] == 1, 'exit_long'] = 1
        dataframe.loc[dataframe['is_bullish'] == 1, 'exit_short'] = 1

        return dataframe
