# --- Freqtrade / Jesse Compatible Strategy Generated by NujinSkills Agent ---
# Strategy: GoatFundedTraderXauusdScalper (The Gold Momentum Train - GIT-15)
# Asset: XAUUSD (Gold Spot / Binance PAXGUSDT)
# Execution: Manual or Bot (1-minute / 3-minute bars)
# Target Prop Firm: Goat Funded Trader (GFT)
# Mandatory Constraints:
#   - 3.0% Daily Drawdown Limit
#   - 6.0% Maximum Total Drawdown
#   - 15.0% Consistency Rule (No single day > 15% of total profit target)
#   - Minimum 2-Minute Holding Lock (Goat Funded Trader anti-arbitrage rule)
#   - Maximum 15-Minute Scalp Cutoff (Prevents session pullback drift)
#   - Sessions: London (07:30-10:30 UTC) & New York (12:45-16:30 UTC)

import numpy as np
import pandas as pd
from pandas import DataFrame
from datetime import datetime, timezone

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass

class GoatFundedTraderXauusdScalper(IStrategy):
    """
    Goat Funded Trader XAUUSD Momentum Train (GIT-15)
    
    Thesis:
    Exploits aggressive institutional order flow expansion out of volatility compression
    during London Open and NY Open liquidity windows. Boards the accelerating momentum ribbon
    (9/21 EMA + 200 EMA macro filter) and takes profits into the momentum exhaustion pocket.
    
    Rules:
    - Entry LONG: London/NY active, Price > 200 EMA, 9 EMA > 21 EMA, Bar Range > 1.2 ATR, Volume Z-Score > 1.0.
    - Entry SHORT: London/NY active, Price < 200 EMA, 9 EMA < 21 EMA, Bar Range > 1.2 ATR, Volume Z-Score > 1.0.
    - Stop Loss: 1.5 * ATR (~$1.50 - $3.00 Gold range, 0.50% account risk).
    - Take Profit: 1:1.8 Risk/Reward (partial at 1:1.5, runner trail behind 21 EMA).
    - Holding Window: MINIMUM 2 bars (120 seconds), MAXIMUM 15 bars (900 seconds).
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = True

    # Goat Funded Trader parameters
    minimal_roi = {
        "0": 0.015,  # +1.5% at start
        "2": 0.008,  # Can only take profit after min 2 minutes!
        "15": 0.0    # Force exit at 15 minutes
    }
    
    # Stop loss ~0.5% (approx 1.5 ATR on Gold)
    stoploss = -0.0055
    trailing_stop = True
    trailing_stop_positive = 0.004
    trailing_stop_positive_offset = 0.006
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Total Bar Range & Wicks
        dataframe['total_range'] = (high - low).replace(0, 1e-6)
        dataframe['body_ratio'] = (close - dataframe['open']).abs() / dataframe['total_range']
        dataframe['upper_wick'] = (high - np.maximum(close, dataframe['open'])) / dataframe['total_range']
        dataframe['lower_wick'] = (np.minimum(close, dataframe['open']) - low) / dataframe['total_range']

        # 2. Moving Average Momentum Ribbon
        dataframe['ema_9'] = close.ewm(span=9, adjust=False).mean()
        dataframe['ema_21'] = close.ewm(span=21, adjust=False).mean()
        dataframe['ema_200'] = close.ewm(span=min(200, len(close)), adjust=False).mean()

        # 3. ATR (14)
        tr = np.maximum(high - low, np.maximum((high - close.shift(1)).abs(), (low - close.shift(1)).abs()))
        dataframe['atr_14'] = tr.rolling(14).mean()

        # 4. Volume Z-Score
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std

        # 5. Session Filter (London 07:30-10:30 UTC & NY 12:45-16:30 UTC)
        if 'timestamp' in dataframe.columns:
            ts = pd.to_datetime(dataframe['timestamp'], unit='s', utc=True)
            minute_of_day = ts.dt.hour * 60 + ts.dt.minute
            dataframe['session_valid'] = (
                ((minute_of_day >= 450) & (minute_of_day <= 630)) | # London: 07:30 to 10:30 UTC
                ((minute_of_day >= 765) & (minute_of_day <= 990))   # NY: 12:45 to 16:30 UTC
            )
        else:
            dataframe['session_valid'] = True

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Long condition:
        # Valid Session + Macro Bullish (Price > 200 EMA) + Fast Ribbon Expansion (9 > 21 EMA) + Vol Surge + Strong Body
        dataframe.loc[
            (
                (dataframe['session_valid'] == True) &
                (dataframe['close'] > dataframe['ema_200']) &
                (dataframe['ema_9'] > dataframe['ema_21']) &
                (dataframe['close'] >= dataframe['ema_9']) &
                (dataframe['volume_zscore'] > 0.8) &
                (dataframe['body_ratio'] > 0.55) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'
        ] = 1

        # Short condition:
        # Valid Session + Macro Bearish (Price < 200 EMA) + Fast Ribbon Expansion (9 < 21 EMA) + Vol Surge + Strong Body
        dataframe.loc[
            (
                (dataframe['session_valid'] == True) &
                (dataframe['close'] < dataframe['ema_200']) &
                (dataframe['ema_9'] < dataframe['ema_21']) &
                (dataframe['close'] <= dataframe['ema_9']) &
                (dataframe['volume_zscore'] > 0.8) &
                (dataframe['body_ratio'] > 0.55) &
                (dataframe['volume'] > 0)
            ),
            'enter_short'
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Exits handled dynamically by minimal_roi, stoploss, and holding timers (min 2m, max 15m)
        dataframe.loc[
            (
                (dataframe['close'] < dataframe['ema_21'])
            ),
            'exit_long'
        ] = 1

        dataframe.loc[
            (
                (dataframe['close'] > dataframe['ema_21'])
            ),
            'exit_short'
        ] = 1

        return dataframe
