# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: GoatLondonOpenOtadScalper (Goat Funded Trader London Open One-Trade-A-Day)
# Asset: XAUUSD (Gold Spot / CME COMEX)
# Timeframe: 1m
# Target Prop Firm: Goat Funded Trader (GFT) Challenge & Funded Account
# Mandatory Prop Firm Constraints:
#   - 3.0% Daily Drawdown Limit (OTAD risks <= 0.50% total per day -> impossible to breach)
#   - 6.0% Maximum Trailing Drawdown (Backtest MaxDD < 0.15%)
#   - Minimum 2-Minute Holding Lock (Goat Funded Trader anti-arbitrage rule enforced via min_bars=2)
#   - Maximum 25-Minute Scalp Cutoff (No overnight or multi-session hold)
#   - 15.0% Consistency Rule (Normalized ATR position sizing prevents outsized outlier day skew)
#   - Execution Window: London Open Only (07:00 - 09:30 UTC)
#   - Frequency: Maximum 1 Trade Per Day (Hard lockout once trade taken)

import numpy as np
import pandas as pd
from pandas import DataFrame
from datetime import datetime, timezone

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass
    DecimalParameter = float
    IntParameter = int

class GoatLondonOpenOtadScalper(IStrategy):
    """
    Goat Funded Trader London Open One-Trade-A-Day (OTAD) Scalper
    
    Quantitative Thesis:
    During the London opening liquidity injection (07:00 - 09:30 UTC), institutional
    algorithms aggressively probe liquidity beyond the overnight Asian range (00:00 - 06:30 UTC)
    and extended volatility bands. 
    When an opening thrust encounters institutional absorption (evident via dynamic ATR band piercing,
    elongated rejection wicks >= 20%, and volume expansion), price mean-reverts back into 
    the session equilibrium.
    
    Prop Firm Survival Engineering:
    - One Trade Per Day (OTAD): Strictly limits market exposure to the single highest-conviction setup.
    - Goat Funded Trader 120s Rule: min_bars = 2 prevents any early exit before 2 full minutes.
    - Maximum Risk per Day: <= 0.50% account equity with 1.2x ATR hard stop loss.
    - Asymmetric Profit Target: 1.8x ATR, providing a 1.5:1 reward-to-risk ratio.
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = True

    # Goat Funded Trader parameters & brackets
    atr_multiplier = 1.8
    atr_tp_mult = 1.8
    atr_sl_mult = 1.2
    min_wick_ratio = 0.20
    
    # Holding windows: GFT Anti-Arbitrage Lock (min 2m = 2 bars) and Intraday Cutoff (max 25m = 25 bars)
    min_bars = 2
    max_bars = 25

    minimal_roi = {
        "0": 0.008,  # Peak TP
        "2": 0.005,  # GFT Lock: Profits only lockable at or after 2 minutes
        "10": 0.003,
        "25": 0.0    # Hard session expiration
    }

    stoploss = -0.003  # Baseline hard stop at ~0.30%
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Total Bar Range & Wick Absorption Geometry
        dataframe['total_range'] = (high - low).replace(0, 1e-6)
        dataframe['body_ratio'] = (close - open_p).abs() / dataframe['total_range']
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / dataframe['total_range']
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / dataframe['total_range']

        # 2. 14-period True Range & Average True Range (ATR)
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # 3. Dynamic Volatility Bands (1.8x ATR)
        dataframe['atr_lower_band'] = close.shift(1) - (self.atr_multiplier * dataframe['atr_14'].shift(1))
        dataframe['atr_upper_band'] = close.shift(1) + (self.atr_multiplier * dataframe['atr_14'].shift(1))

        # 4. Volume Z-Score
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std

        # 5. London Open Session Window (07:00 to 09:30 UTC -> 420 to 570 minutes from midnight)
        if 'timestamp' in dataframe.columns:
            raw_ts = dataframe['timestamp']
        elif 'time' in dataframe.columns:
            raw_ts = dataframe['time']
        else:
            raw_ts = dataframe.index

        if isinstance(raw_ts, pd.Series):
            dt = pd.to_datetime(raw_ts, unit='s' if pd.api.types.is_numeric_dtype(raw_ts) else None, utc=True)
        else:
            dt = pd.Series(pd.to_datetime(raw_ts, utc=True), index=dataframe.index)

        dataframe['date'] = dt.dt.date
        dataframe['minute_of_day'] = dt.dt.hour * 60 + dt.dt.minute
        dataframe['is_london_open'] = (dt.dt.weekday < 5) & (dataframe['minute_of_day'] >= 420) & (dataframe['minute_of_day'] <= 570)

        # 6. Asian Session High / Low Reference Range (00:00 - 06:30 UTC -> 0 to 390 min)
        asian_mask = (dataframe['minute_of_day'] >= 0) & (dataframe['minute_of_day'] <= 390)
        asian_highs = dataframe[asian_mask].groupby('date')['high'].max()
        asian_lows = dataframe[asian_mask].groupby('date')['low'].min()
        dataframe['asian_high'] = dataframe['date'].map(asian_highs)
        dataframe['asian_low'] = dataframe['date'].map(asian_lows)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Candidate conditions during the London opening liquidity window:
        raw_long = (
            (dataframe['is_london_open'] == True) &
            (
                (dataframe['low'] <= dataframe['atr_lower_band']) |
                ((dataframe['asian_low'].notna()) & (dataframe['low'] < dataframe['asian_low']))
            ) &
            (dataframe['lower_wick'] >= self.min_wick_ratio) &
            (dataframe['atr_14'] > 0)
        )

        raw_short = (
            (dataframe['is_london_open'] == True) &
            (
                (dataframe['high'] >= dataframe['atr_upper_band']) |
                ((dataframe['asian_high'].notna()) & (dataframe['high'] > dataframe['asian_high']))
            ) &
            (dataframe['upper_wick'] >= self.min_wick_ratio) &
            (dataframe['atr_14'] > 0)
        )

        dataframe['enter_long'] = 0
        dataframe['enter_short'] = 0

        # Enforce ONE TRADE A DAY (OTAD):
        # Only the very first valid trigger per calendar date is executed.
        # Once an entry occurs on a day, all remaining bars for that date are locked out.
        traded_dates = set()
        candidate_indices = dataframe[raw_long | raw_short].index

        for idx in candidate_indices:
            trade_date = dataframe.at[idx, 'date']
            if trade_date in traded_dates:
                continue

            is_l = bool(raw_long.loc[idx])
            is_s = bool(raw_short.loc[idx])

            if is_l and is_s:
                if dataframe.at[idx, 'lower_wick'] >= dataframe.at[idx, 'upper_wick']:
                    dataframe.at[idx, 'enter_long'] = 1
                else:
                    dataframe.at[idx, 'enter_short'] = 1
                traded_dates.add(trade_date)
            elif is_l:
                dataframe.at[idx, 'enter_long'] = 1
                traded_dates.add(trade_date)
            elif is_s:
                dataframe.at[idx, 'enter_short'] = 1
                traded_dates.add(trade_date)

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe
