# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: GoldLiquiditySweepAtrScalper (XAUUSD 1-Minute Liquidity Sweep & ATR Rebound)
# Asset: XAU/USD (Gold Spot / CFD)
# Timeframe: 1m
# Reference Taxonomy: Part 1.1 (Liquidity Sweeps / SMC) & Part 2.1 (Institutional Absorption)
# Mandatory Prop Firm & Nujin Gates:
#   - Net Sharpe >= 1.80
#   - Max Drawdown <= 4.5%
#   - Win Rate >= 50%
#   - Deflated Sharpe (DSR) >= 0.95
#   - 4-Factor Confluence:
#       1. Active London & New York Liquidity Windows (07:00 - 18:00 UTC)
#       2. Volatility Envelope Dip Piercing (Low <= Close[t-1] - 2.2 * ATR)
#       3. Institutional Order Flow Absorption (Lower Wick >= 0.26 + Volume Z-Score >= 0.6)
#       4. Dynamic Asymmetric Brackets: 1.8x ATR Target / 1.1x ATR Stop Loss (RR = 1:1.64)

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass

class GoldLiquiditySweepAtrScalper(IStrategy):
    """
    Gold Liquidity Sweep & ATR Rebound Scalper (XAUUSD 1-Minute)

    Quantitative Rationale:
    Gold possesses deep institutional liquidity but experiences frequent stop-loss hunting
    sweeps around session boundaries. When price pierces below dynamic volatility bounds
    (2.2x ATR below prior close) and prints an aggressive lower rejection wick on elevated
    relative volume, passive institutional limit bids absorb the panic sellers.
    We enter long for a high-probability mean-reverting expansion back to VWAP.
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = False

    # Risk Management & Dynamic Brackets calibrated for Gold (XAUUSD 1m)
    atr_multiplier = 2.0
    atr_tp_mult = 1.5
    atr_sl_mult = 1.2
    min_wick_ratio = 0.25
    max_bars = 6
    min_bars = 1

    minimal_roi = {
        "0": 0.005,
        "2": 0.003,
        "6": 0.0
    }

    stoploss = -0.003
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Bar Geometry & Wick Physics
        total_range = (high - low).replace(0, 1e-6)
        dataframe['total_range'] = total_range
        dataframe['body_ratio'] = (close - open_p).abs() / total_range
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / total_range
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / total_range

        # 2. True Range & 14-period ATR
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # 3. Dynamic Volatility Envelope (Deep Volatility Band)
        dataframe['atr_lower_band'] = close.shift(1) - (self.atr_multiplier * dataframe['atr_14'].shift(1))

        # 4. Volume Z-Score & Order Flow Delta Proxy
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std
        dataframe['delta_proxy'] = ((close - open_p) / total_range) * volume

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # LONG ENTRY:
        # 1. Deep Volatility Penetration (Low <= ATR Lower Band)
        # 2. Lower wick absorption >= min_wick_ratio (0.28)
        # 3. Elevated Volume Z-Score >= 0.8
        # 4. Valid positive ATR
        long_cond = (
            (dataframe['low'] <= dataframe['atr_lower_band']) &
            (dataframe['lower_wick'] >= self.min_wick_ratio) &
            (dataframe['volume_zscore'] >= 0.8) &
            (dataframe['atr_14'] > 0)
        )
        dataframe.loc[long_cond, 'enter_long'] = 1
        dataframe['enter_short'] = 0

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe
