# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: OpeningFlushReversalScalper (S&P 500 Futures / ES 1-Minute Intraday Reversal)
# Reference: https://www.youtube.com/shorts/dnOPOEYq6fM
# Asset: S&P 500 (ES / SPY / MES / US500)
# Timeframe: 1m
# Mandatory Prop Firm Constraints:
#   - Max Drawdown <= 4.5% (Prop Firm Challenge Limit)
#   - Max Position Risk: 0.5% Account Equity
#   - 4-Factor Confluence:
#       1. Pre-Market / Overnight Key Support & Resistance Zones
#       2. Opening Session Reversal Timings (15m-45m post-open: 9:45 - 10:15 EST)
#       3. Strong Unhealthy Flush into Liquidity Zone
#       4. Market Structure Shift (Inverted/Regular Head & Shoulders Neckline Breakout)

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass
    DecimalParameter = float
    IntParameter = int

class OpeningFlushReversalScalper(IStrategy):
    """
    Opening Flush Reversal Scalper (S&P 500 / ES 1-Minute)
    
    Quantitative Thesis:
    Captures institutional liquidity sweeps at the S&P 500 opening bell.
    Retail traders panic buy/sell during aggressive opening flushes (9:30-9:45 EST).
    Price pierces pre-market overnight support or resistance zones.
    Institutional limit absorption halts the move, forming a Head & Shoulders
    structure (Inverted H&S for Longs, Regular H&S for Shorts) with higher-low / lower-high
    right shoulders and strong expansion breakout candles breaking the local neckline.
    
    Execution Rules:
    - Pre-market Zone: Rolling 120-bar lookback prior to the opening bell.
    - Timing Windows: US RTH Open (13:45 - 14:20 UTC / 9:45 - 10:20 EST) & London Open (07:15 - 07:50 UTC).
    - Factor 1: Flush piercing pre-market support (Long) or resistance (Short).
    - Factor 2: Reversal timing window (15m-45m post-open).
    - Factor 3: Market structure shift with higher-low shoulder and lower-wick absorption.
    - Factor 4: Bullish/bearish expansion candle breaking the local neckline.
    - Exits: Dynamic brackets with Stop Loss below Head/Shoulder extreme, targeting 1.8x to 2.2x RR.
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = True

    # Risk Management & Dynamic Brackets calibrated for S&P 500 (ES 1m)
    atr_multiplier = 1.6
    atr_tp_mult = 2.2
    atr_sl_mult = 1.5
    min_wick_ratio = 0.20
    max_risk_pct = 0.005
    max_bars = 44
    min_bars = 1

    minimal_roi = {
        "0": 0.0035,
        "15": 0.0020,
        "30": 0.0010,
        "44": 0.0
    }
    
    stoploss = -0.0015
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']

        # 1. Bar Geometry & Candle Ratios
        dataframe['total_range'] = (high - low).replace(0, 1e-6)
        dataframe['body_ratio'] = (close - open_p).abs() / dataframe['total_range']
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / dataframe['total_range']
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / dataframe['total_range']

        # 2. True Range & 14-period ATR
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # 3. Time Filtering: Opening Session Reversal Timings
        # US RTH Open (9:30 EST = 13:30 UTC): Reversal window 9:45 - 10:20 EST (13:45 - 14:20 UTC)
        # London Open (08:00 BST = 07:00 UTC): Reversal window 07:15 - 07:50 UTC
        if 'timestamp' in dataframe.columns:
            dt = pd.to_datetime(dataframe['timestamp'], unit='s', utc=True)
        elif 'time' in dataframe.columns:
            dt = pd.to_datetime(dataframe['time'], unit='s', utc=True)
        elif isinstance(dataframe.index, pd.DatetimeIndex):
            dt = dataframe.index.tz_convert('UTC') if dataframe.index.tz is not None else dataframe.index.tz_localize('UTC')
        else:
            dt = pd.to_datetime(dataframe.index, utc=True)

        if hasattr(dt, 'dt'):
            dataframe['time_min'] = dt.dt.hour * 60 + dt.dt.minute
        else:
            dataframe['time_min'] = dt.hour * 60 + dt.minute
        us_reversal = (dataframe['time_min'] >= 825) & (dataframe['time_min'] <= 860)
        lon_reversal = (dataframe['time_min'] >= 435) & (dataframe['time_min'] <= 470)
        dataframe['is_reversal_window'] = us_reversal | lon_reversal

        # 4. Factor 1: Pre-Market Support & Resistance (120-bar lookback shifted by 20 bars)
        dataframe['premarket_support'] = low.shift(20).rolling(120).min()
        dataframe['premarket_resistance'] = high.shift(20).rolling(120).max()

        # Dynamic Volatility Envelopes
        dataframe['atr_lower_band'] = close.shift(1) - (self.atr_multiplier * dataframe['atr_14'].shift(1))
        dataframe['atr_upper_band'] = close.shift(1) + (self.atr_multiplier * dataframe['atr_14'].shift(1))

        # 5. Factor 2: Opening Flush Identification (Piercing Pre-Market Extremes)
        recent_low_15 = low.rolling(15).min()
        recent_high_15 = high.rolling(15).max()
        dataframe['flush_down'] = (recent_low_15 <= dataframe['premarket_support'] * 1.0005)
        dataframe['flush_up']   = (recent_high_15 >= dataframe['premarket_resistance'] * 0.9995)

        # 6. Factor 3 & 4: Inverted Head & Shoulders (LONG) & Regular Head & Shoulders (SHORT)
        # LONG: Head is lowest low in 12 bars; Right Shoulder is higher low; Neckline is local swing high
        head_low = low.shift(3).rolling(12).min()
        shoulder_low = low.rolling(3).min()
        right_shoulder = (shoulder_low > head_low) & (shoulder_low <= head_low + 2.0 * dataframe['atr_14'])
        neckline_long = high.shift(1).rolling(5).max()
        dataframe['long_neckline_break'] = (
            (close > neckline_long) &
            right_shoulder &
            (close > open_p)
        )

        # SHORT: Head is highest high in 12 bars; Right Shoulder is lower high; Neckline is local swing low
        head_high = high.shift(3).rolling(12).max()
        shoulder_high = high.rolling(3).max()
        right_shoulder_short = (shoulder_high < head_high) & (shoulder_high >= head_high - 2.0 * dataframe['atr_14'])
        neckline_short = low.shift(1).rolling(5).min()
        dataframe['short_neckline_break'] = (
            (close < neckline_short) &
            right_shoulder_short &
            (close < open_p)
        )

        # 7. Structural Stop Loss & Take Profit Levels (Video specification: Stop below head/shoulder, 2.0x TP)
        long_risk = (close - np.minimum(head_low - 0.5, close - 1.8 * dataframe['atr_14'])).replace(0, 1.0)
        dataframe['long_sl'] = np.minimum(head_low - 0.5, close - 1.8 * dataframe['atr_14'])
        dataframe['long_tp'] = close + 2.0 * long_risk

        short_risk = (np.maximum(head_high + 0.5, close + 1.8 * dataframe['atr_14']) - close).replace(0, 1.0)
        dataframe['short_sl'] = np.maximum(head_high + 0.5, close + 1.8 * dataframe['atr_14'])
        dataframe['short_tp'] = close - 2.0 * short_risk

        dataframe['structural_sl'] = np.where(dataframe['long_neckline_break'], dataframe['long_sl'], dataframe['short_sl'])
        dataframe['structural_tp'] = np.where(dataframe['long_neckline_break'], dataframe['long_tp'], dataframe['short_tp'])

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # LONG Entry: In Reversal Window + Flush Down + Inverted H&S Neckline Breakout
        dataframe.loc[
            (dataframe['is_reversal_window']) &
            (dataframe['flush_down']) &
            (dataframe['long_neckline_break']) &
            (dataframe['atr_14'] > 0),
            'enter_long'
        ] = 1

        # SHORT Entry: In Reversal Window + Flush Up + Regular H&S Neckline Breakdown
        dataframe.loc[
            (dataframe['is_reversal_window']) &
            (dataframe['flush_up']) &
            (dataframe['short_neckline_break']) &
            (dataframe['atr_14'] > 0),
            'enter_short'
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe
