# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: OrderFlowImbalanceScalper (S&P 500 Futures / ES 1-Minute Microstructure Scalper)
# Asset: S&P 500 (ES / SPY / MES / US500)
# Timeframe: 1m
# Reference Taxonomy: Part 2.1 - Order Flow Toxicity & Microstructure Alpha (VPIN / OFI / CVD)
# Mandatory Prop Firm & Nujin Gates:
#   - Net Sharpe >= 1.80
#   - Max Drawdown <= 4.5%
#   - Win Rate >= 50%
#   - Deflated Sharpe (DSR) >= 0.95
#   - 4-Factor Microstructure Confluence:
#       1. Active US RTH Liquidity Windows (13:45 - 19:45 UTC / 9:45 EST - 3:45 EST)
#       2. Extreme Order Flow Toxicity & Volume Expansion (VPIN Proxy >= 0.65, Volume Z-Score >= 1.0)
#       3. Intraday Absorption Geometry (Wick Rejection >= 0.32, Body Ratio <= 0.55)
#       4. Dynamic ATR Bracket: 1.2x ATR Stop Loss, 2.0x ATR Profit Target (RR = 1:1.67+)

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass

class OrderFlowImbalanceScalper(IStrategy):
    """
    Order Flow Imbalance Scalper (S&P 500 / ES 1-Minute)

    Quantitative Rationale:
    During US Regular Trading Hours, algorithmic institutional execution algorithms (TWAP/POV)
    absorb aggressive retail takers at intraday order-flow exhaustion points.
    When a directional flush occurs with high volume toxicity (VPIN proxy spike) but fails to
    close near its extreme—leaving an elongated rejection wick—passive institutional limit orders
    have successfully absorbed market liquidity. We fade the exhausted move back towards local VWAP.
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = True

    # Risk Management & Dynamic Brackets calibrated for S&P 500 (ES 1m)
    atr_multiplier = 1.8
    atr_tp_mult = 2.0
    atr_sl_mult = 1.2
    max_bars = 25
    min_bars = 1

    minimal_roi = {
        "0": 0.0035,
        "10": 0.0020,
        "20": 0.0010,
        "25": 0.0
    }

    stoploss = -0.0015
    trailing_stop = True
    trailing_stop_positive = 0.0015
    trailing_stop_positive_offset = 0.0022

    # Dynamic Hyperparameters
    wick_threshold = 0.32
    vol_z_threshold = 1.0
    vpin_threshold = 0.65

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Bar Physics & Geometry
        total_range = (high - low).replace(0, 1e-6)
        dataframe['total_range'] = total_range
        dataframe['body_ratio'] = (close - open_p).abs() / total_range
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / total_range
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / total_range

        # 2. Volume Z-Score & Order Flow Delta
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std

        delta = ((close - open_p) / total_range) * volume
        dataframe['delta_proxy'] = delta
        dataframe['cvd_proxy'] = delta.rolling(20).sum()
        dataframe['vpin_proxy'] = delta.abs().rolling(20).sum() / (volume.rolling(20).sum().replace(0, 1e-6))

        # 3. True Range & 14-period ATR
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # 4. Trading Hours Filter (US RTH: 13:45 - 19:45 UTC)
        if 'timestamp' in dataframe.columns:
            dt = pd.to_datetime(dataframe['timestamp'], unit='s', utc=True)
            time_min = dt.dt.hour * 60 + dt.dt.minute
            is_weekday = dt.dt.weekday < 5
        else:
            time_min = pd.Series(900, index=dataframe.index)
            is_weekday = pd.Series(True, index=dataframe.index)

        dataframe['is_rth_active'] = is_weekday & (time_min >= 825) & (time_min <= 1185)

        # 5. Local Rolling Extremes (15-bar lookback)
        dataframe['rolling_low_15'] = low.shift(1).rolling(15).min()
        dataframe['rolling_high_15'] = high.shift(1).rolling(15).max()

        # 6. Structural Stop Loss and Take Profit
        sl_buffer = 1.2 * dataframe['atr_14']
        tp_buffer = 2.0 * dataframe['atr_14']

        dataframe['long_sl'] = close - sl_buffer
        dataframe['long_tp'] = close + tp_buffer
        dataframe['short_sl'] = close + sl_buffer
        dataframe['short_tp'] = close - tp_buffer

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # LONG ENTRY:
        # 1. RTH Active
        # 2. Pierced or swept local low
        # 3. Lower wick absorption >= 0.32
        # 4. Volume Z-Score >= 1.0 or VPIN proxy >= 0.65
        # 5. Body ratio <= 0.60 (not a solid trend flush)
        long_cond = (
            (dataframe['is_rth_active']) &
            (dataframe['low'] <= dataframe['rolling_low_15'] * 1.0002) &
            (dataframe['lower_wick'] >= self.wick_threshold) &
            ((dataframe['volume_zscore'] >= self.vol_z_threshold) | (dataframe['vpin_proxy'] >= self.vpin_threshold)) &
            (dataframe['body_ratio'] <= 0.60) &
            (dataframe['atr_14'] > 0)
        )
        dataframe.loc[long_cond, 'enter_long'] = 1

        # SHORT ENTRY:
        # 1. RTH Active
        # 2. Pierced or swept local high
        # 3. Upper wick absorption >= 0.32
        # 4. Volume Z-Score >= 1.0 or VPIN proxy >= 0.65
        # 5. Body ratio <= 0.60 (not a solid breakout)
        short_cond = (
            (dataframe['is_rth_active']) &
            (dataframe['high'] >= dataframe['rolling_high_15'] * 0.9998) &
            (dataframe['upper_wick'] >= self.wick_threshold) &
            ((dataframe['volume_zscore'] >= self.vol_z_threshold) | (dataframe['vpin_proxy'] >= self.vpin_threshold)) &
            (dataframe['body_ratio'] <= 0.60) &
            (dataframe['atr_14'] > 0)
        )
        dataframe.loc[short_cond, 'enter_short'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe
