# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: PropFirmAtrHybridScalper (Trader MNQ's ATR Hybrid Scalper)
# Reference: IQCapital Prop Firm Trader MNQ Strategy (https://youtu.be/snaP5117MxI)
# Asset: Micro NASDAQ (MNQ) / BTCUSDT / Equity Futures
# Timeframe: 5m / 15m
# Mandatory Prop Firm Constraints:
#   - Max Drawdown <= 4.5% (Strict Prop Firm Challenge & Funded account limit)
#   - Max Risk per Position: 0.5% (Funded) to 1.0% (Challenge)
#   - Asymmetric Execution: Intra-bar ATR Dip Buying (Long) vs. Liquidity Exhaustion Fading (Short)
#   - Macro Regime Filter: Short only on Bearish / Red Higher-Timeframe Days

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass

class PropFirmAtrHybridScalper(IStrategy):
    """
    Prop Firm ATR Hybrid Scalper (Trader MNQ)
    
    Thesis:
    Indices and high-liquidity crypto assets exhibit structural upward drift and volatility asymmetry.
    Direct inversion of long dip-buying strategies fails on shorts. Trader MNQ decouples long and short:
    
    1. Long Model (Mean-Reversion Volatility Dip):
       - Dynamic Lower ATR Band: LowerBand = Close[t-1] - 3.1 * ATR14[t-1]
       - Entry: Limit order resting at LowerBand. Triggered when current Low <= LowerBand.
       - Exit TP: Entry + 2.0 * ATR14[t-1] (Limit order target)
       - Exit SL: Entry - 1.5 * ATR14[t-1] (Fixed protective stop, RR = 1.33:1)
       - Filter: Skip chaotic opening session candle.
       
    2. Short Model (Liquidity Sweep & Wick Exhaustion Fading):
       - Trigger Candle: Upper wick >= 2.0 * Body, Lower wick <= 0.12 * Upper wick, Upper wick >= 38%
       - Macro Filter (The Critical Upgrade): Previous daily candle closed RED / bearish.
       - Entry: Market order at Open of next candle following the rejection bar.
       - Exit: Fast 1-bar time exit (5m-15m window) OR 1.5 ATR emergency protective stop.
       
    3. Position Sizing:
       - Volatility-adjusted sizing: Position Size = (Account Balance * 0.005) / (1.5 * ATR)
       - Protects the 0.5% max risk per trade prop firm hurdle.
    """
    INTERFACE_VERSION = 3
    timeframe = '15m'
    can_short = True

    # Prop firm parameters
    atr_multiplier = 3.1
    atr_tp_mult = 2.0
    atr_sl_mult = 1.5
    max_risk_pct = 0.005 # 0.5% account risk per trade
    
    minimal_roi = {
        "0": 0.040,
        "4": 0.020,
        "8": 0.010,
        "16": 0.0
    }
    
    stoploss = -0.015
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Bar Geometry
        dataframe['total_range'] = (high - low).replace(0, 1e-6)
        dataframe['body_ratio'] = (close - open_p).abs() / dataframe['total_range']
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / dataframe['total_range']
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / dataframe['total_range']

        # 2. True Range & ATR(14)
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # 3. Dynamic ATR Bands (Anchored to previous candle close)
        dataframe['atr_lower_band'] = close.shift(1) - (self.atr_multiplier * dataframe['atr_14'].shift(1))
        dataframe['atr_upper_band'] = close.shift(1) + (self.atr_multiplier * dataframe['atr_14'].shift(1))

        # 4. Volume Z-score
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std

        # 5. Macro Daily Bearish Regime Filter (24-hour return < 0)
        daily_bars = 96 if self.timeframe == '15m' else (288 if self.timeframe == '5m' else 24)
        dataframe['daily_return'] = (close - close.shift(daily_bars)) / close.shift(daily_bars).replace(0, 1e-6)
        dataframe['macro_bearish_regime'] = dataframe['daily_return'] < 0.0

        # 6. Objective Shooting Star Definition
        dataframe['is_shooting_star'] = (
            (dataframe['upper_wick'] >= 2.0 * dataframe['body_ratio']) &
            (dataframe['lower_wick'] <= 0.12 * dataframe['upper_wick']) &
            (dataframe['upper_wick'] >= 0.38)
        )

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Long Entry: Low clips the lower ATR band (Intra-bar dynamic envelope touch)
        dataframe.loc[
            (dataframe['low'] <= dataframe['atr_lower_band']) &
            (dataframe['atr_14'] > 0),
            'enter_long'
        ] = 1

        # Short Entry: Exhaustion shooting star wick rejection in a macro bearish regime
        dataframe.loc[
            (dataframe['is_shooting_star'].shift(1) == True) &
            (dataframe['macro_bearish_regime'] == True),
            'enter_short'
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Exits handled via dynamic ATR take-profit & stop-loss brackets
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe

    def custom_position_size(self, capital: float, current_atr: float) -> float:
        """Computes dynamic contract sizing so stop-loss strictly risks 0.5% account equity."""
        sl_distance = self.atr_sl_mult * current_atr
        if sl_distance <= 0:
            return 1.0
        risk_capital = capital * self.max_risk_pct
        target_size = risk_capital / sl_distance
        return target_size
