# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: PropFirmAtrHybridScalperXauusd (Trader MNQ ATR Scalper on Gold)
# Reference: IQCapital Prop Firm Trader MNQ Strategy (https://youtu.be/snaP5117MxI)
# Asset: XAUUSD (Gold Spot / CFD)
# Timeframe: 1m / 5m
# Mandatory Prop Firm Constraints:
#   - Max Drawdown <= 4.5% (Prop Firm Challenge Limit)
#   - Max Position Risk: 0.5% Account Equity
#   - Asymmetric Long ATR Dip Limit Fill vs. Short Shooting Star Rejection

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass

class PropFirmAtrHybridScalperXauusd(IStrategy):
    """
    Prop Firm ATR Hybrid Scalper on Gold (XAUUSD)
    
    Thesis:
    Applies Trader MNQ's volatility envelope dip buying to cash gold spot liquidity.
    Gold exhibits high intraday noise but explosive expansion when piercing volatility bands.
    
    Rules:
    - Long Entry: Limit order at LowerBand = Close[t-1] - 2.6 * ATR14[t-1]
    - Short Entry: Exhaustion shooting star wick rejection in a macro daily bearish regime.
    - Exits: +1.8x ATR Target / -1.2x ATR Stop-loss (RR = 1.5:1).
    - Position Sizing: (Account Balance * 0.005) / (1.2 * ATR).
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = True

    atr_multiplier = 2.6
    atr_tp_mult = 1.8
    atr_sl_mult = 1.2
    max_risk_pct = 0.005
    
    minimal_roi = {
        "0": 0.005,
        "2": 0.003,
        "6": 0.0
    }
    
    stoploss = -0.003
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        dataframe['total_range'] = (high - low).replace(0, 1e-6)
        dataframe['body_ratio'] = (close - open_p).abs() / dataframe['total_range']
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / dataframe['total_range']
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / dataframe['total_range']

        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        dataframe['atr_lower_band'] = close.shift(1) - (self.atr_multiplier * dataframe['atr_14'].shift(1))
        dataframe['atr_upper_band'] = close.shift(1) + (self.atr_multiplier * dataframe['atr_14'].shift(1))

        # 1440 bars in 24h on 1m chart
        dataframe['daily_return'] = (close - close.shift(1440)) / close.shift(1440).replace(0, 1e-6)
        dataframe['macro_bearish_regime'] = dataframe['daily_return'] < 0.0

        dataframe['is_shooting_star'] = (
            (dataframe['upper_wick'] >= 1.8 * dataframe['body_ratio']) &
            (dataframe['lower_wick'] <= 0.15 * dataframe['upper_wick']) &
            (dataframe['upper_wick'] >= 0.35)
        )

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (dataframe['low'] <= dataframe['atr_lower_band']) &
            (dataframe['atr_14'] > 0),
            'enter_long'
        ] = 1

        dataframe.loc[
            (dataframe['is_shooting_star'].shift(1) == True) &
            (dataframe['macro_bearish_regime'] == True),
            'enter_short'
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe
