# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: XauLiquidityWallsDisplacementScalper
# Asset: XAUUSD (Gold Spot 1m)
# Based on: TradingIQ Liquidity Walls + Tap & Displacement Confirmation + 2:1 RRR
# Mandatory Prop Firm Constraints:
#   - Max Drawdown <= 4.5%
#   - Sharpe >= 1.8
#   - Win Rate >= 50%
#   - DSR >= 0.95
#   - 2:1 RRR Structural Bracket Exit

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass

class XauLiquidityWallsDisplacementScalper(IStrategy):
    INTERFACE_VERSION = 3
    timeframe = "1m"
    can_short = True

    # 2:1 RRR targets
    minimal_roi = {}
    atr_tp_mult = 2.0
    atr_sl_mult = 1.0
    
    stoploss = -0.004
    trailing_stop = False
    max_bars = 25

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe["close"]
        open_p = dataframe["open"]
        high = dataframe["high"]
        low = dataframe["low"]
        volume = dataframe["volume"]

        # 1. Bar geometry & Wicks
        total_range = (high - low).replace(0, 1e-6)
        dataframe["body_ratio"] = (close - open_p).abs() / total_range
        dataframe["lower_wick"] = (np.minimum(close, open_p) - low) / total_range
        dataframe["upper_wick"] = (high - np.maximum(close, open_p)) / total_range

        # 2. ATR 14
        prev_close = close.shift(1).fillna(open_p)
        tr = np.maximum(high - low, np.maximum((high - prev_close).abs(), (low - prev_close).abs()))
        atr = tr.rolling(14).mean().bfill()
        dataframe["atr_14"] = atr

        # 3. Volume Z-Score Surge
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe["volume_zscore"] = (volume - vol_mean) / vol_std

        # 4. Order Flow Delta & Linear Regression (TradingIQ Liquidity Walls Math)
        mintick = 0.01
        move_ticks = (close - open_p) / mintick
        direction = np.sign(close - prev_close).fillna(0)
        delta = volume * direction
        
        reg_len = 100
        mean_move = move_ticks.rolling(reg_len).mean()
        mean_delta = delta.rolling(reg_len).mean()
        std_move = move_ticks.rolling(reg_len).std().replace(0, 1e-6)
        std_delta = delta.rolling(reg_len).std().replace(0, 1e-6)
        
        corr = move_ticks.rolling(reg_len).corr(delta).fillna(0)
        beta = (corr * (std_move / std_delta)).fillna(0)
        alpha = (mean_move.shift(1) - beta * mean_delta.shift(1)).fillna(0)

        expected_ticks = alpha + beta * delta
        fail_ticks = np.sign(expected_ticks) * (expected_ticks - move_ticks)

        fail_mean = fail_ticks.rolling(reg_len).mean()
        fail_std = fail_ticks.rolling(reg_len).std().replace(0, 1e-6)
        z_score = ((fail_ticks - fail_mean) / fail_std).fillna(0)
        dataframe["z_score"] = z_score
        dataframe["absorb_side"] = np.sign(expected_ticks)

        # 5. Session Filter (Active London & NY sessions: 07:00 to 18:00 UTC)
        if "timestamp" in dataframe.columns:
            ts = pd.to_datetime(dataframe["timestamp"], unit="s", utc=True)
            minute_of_day = ts.dt.hour * 60 + ts.dt.minute
            is_weekday = ts.dt.weekday < 5
            # Session between 07:00 UTC (420m) and 18:00 UTC (1080m)
            dataframe["session_valid"] = is_weekday & (minute_of_day >= 420) & (minute_of_day <= 1080)
        else:
            dataframe["session_valid"] = True

        dataframe["ema_50"] = close.ewm(span=50).mean().bfill()
        dataframe["macro_trend"] = np.where(close > dataframe["ema_50"], 1, -1)

        # Pre-allocate signal & execution arrays
        n = len(dataframe)
        enter_long = np.zeros(n, dtype=int)
        enter_short = np.zeros(n, dtype=int)
        custom_entry_price = np.full(n, np.nan)
        structural_sl = np.full(n, np.nan)
        structural_tp = np.full(n, np.nan)

        active_zones = []

        high_vals = high.values
        low_vals = low.values
        close_vals = close.values
        open_vals = open_p.values
        atr_vals = atr.values
        z_vals = z_score.values
        absorb_vals = dataframe["absorb_side"].values
        l_wick_vals = dataframe["lower_wick"].values
        u_wick_vals = dataframe["upper_wick"].values
        vol_z_vals = dataframe["volume_zscore"].values
        sess_vals = dataframe["session_valid"].values

        for i in range(reg_len, n):
            h_i = high_vals[i]
            l_i = low_vals[i]
            c_i = close_vals[i]
            o_i = open_vals[i]
            atr_i = atr_vals[i]
            z_i = z_vals[i]
            side_i = absorb_vals[i]
            l_wick = l_wick_vals[i]
            u_wick = u_wick_vals[i]
            vz = vol_z_vals[i]
            sess_ok = sess_vals[i]

            # 1. Clean up broken / breached zones
            active_zones = [
                z for z in active_zones
                if not (z["side"] == 1 and h_i > z["top"]) and
                   not (z["side"] == -1 and l_i < z["bottom"]) and
                   (i - z["created_bar"] < 180)
            ]

            # 2. Form new liquidity zone if z >= 2.0
            if z_i >= 2.0:
                if side_i == 1:
                    active_zones.append({
                        "top": h_i + 0.8 * atr_i,
                        "bottom": h_i,
                        "side": 1,
                        "tapped": False,
                        "tap_extreme": h_i,
                        "displaced": False,
                        "created_bar": i
                    })
                elif side_i == -1:
                    active_zones.append({
                        "top": l_i,
                        "bottom": l_i - 0.8 * atr_i,
                        "side": -1,
                        "tapped": False,
                        "tap_extreme": l_i,
                        "displaced": False,
                        "created_bar": i
                    })

            if not sess_ok:
                continue

            # 3. Check for Tap & Displacement with momentum confirmation
            # Confirmation requires bullish candle/wick + momentum surge (volume_zscore >= 0.2)
            ema_val = dataframe["ema_50"].values[i]
            is_downtrend = c_i < ema_val
            is_uptrend = c_i > ema_val

            # In downtrend, counter-trend longs require stronger rejection wick to avoid knife-catching
            # In uptrend, counter-trend shorts require stronger rejection wick to avoid steamrolling
            bullish_conf = ((c_i > o_i and l_wick >= (0.30 if is_downtrend else 0.15)) or (l_wick >= (0.40 if is_downtrend else 0.25))) and (vz >= (0.3 if is_downtrend else 0.1))
            bearish_conf = ((c_i < o_i and u_wick >= (0.30 if is_uptrend else 0.15)) or (u_wick >= (0.40 if is_uptrend else 0.25))) and (vz >= (0.3 if is_uptrend else 0.1))

            for z in active_zones:
                # ── DEMAND / SUPPORT ZONE (LONG SETUP) ──
                if z["side"] == -1:
                    if l_i <= z["top"] and l_i >= z["bottom"]:
                        z["tapped"] = True
                        z["tap_extreme"] = min(z["tap_extreme"], l_i)

                    if z["tapped"] and not z["displaced"]:
                        if h_i >= z["top"] and bullish_conf:
                            entry_p = round(z["top"], 2)
                            sl_p = round(min(z["tap_extreme"], z["bottom"]) - 0.15 * atr_i, 2)
                            risk = entry_p - sl_p
                            if 0.20 <= risk <= 3.0 * atr_i:
                                tp_p = round(entry_p + 2.0 * risk, 2) # Strict 2:1 RRR
                                enter_long[i] = 1
                                custom_entry_price[i] = entry_p
                                structural_sl[i] = sl_p
                                structural_tp[i] = tp_p
                                z["displaced"] = True
                                break

                # ── SUPPLY / RESISTANCE ZONE (SHORT SETUP) ──
                elif z["side"] == 1:
                    if h_i >= z["bottom"] and h_i <= z["top"]:
                        z["tapped"] = True
                        z["tap_extreme"] = max(z["tap_extreme"], h_i)

                    if z["tapped"] and not z["displaced"]:
                        if l_i <= z["bottom"] and bearish_conf:
                            entry_p = round(z["bottom"], 2)
                            sl_p = round(max(z["tap_extreme"], z["top"]) + 0.15 * atr_i, 2)
                            risk = sl_p - entry_p
                            if 0.20 <= risk <= 3.0 * atr_i:
                                tp_p = round(entry_p - 2.0 * risk, 2) # Strict 2:1 RRR
                                enter_short[i] = 1
                                custom_entry_price[i] = entry_p
                                structural_sl[i] = sl_p
                                structural_tp[i] = tp_p
                                z["displaced"] = True
                                break

        dataframe["enter_long"] = enter_long
        dataframe["enter_short"] = enter_short
        dataframe["custom_entry_price"] = custom_entry_price
        dataframe["structural_sl"] = structural_sl
        dataframe["structural_tp"] = structural_tp

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe["exit_long"] = 0
        dataframe["exit_short"] = 0
        return dataframe
