# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: XauMtfEngulfingScalper (Multi-Timeframe 15m Engulfing & 1m Liquidity Absorption Scalper)
# Asset: XAU/USD (Gold Spot / CFD)
# Timeframe: 1m (with 15m Higher Timeframe Confluence)
# Target Trade Duration: 5 to 15 Minutes (1 to 10 bars on 1m chart)
# Mandatory Prop Firm & Nujin Gates:
#   - Net Sharpe >= 1.80
#   - Max Drawdown <= 4.5%
#   - Win Rate >= 50%
#   - Deflated Sharpe (DSR) >= 0.95
#   - Trade Horizon: min_bars = 1, max_bars = 10 (Intraday Scalp Cutoff)

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass
    DecimalParameter = float
    IntParameter = int

class XauMtfEngulfingScalper(IStrategy):
    """
    XauMtfEngulfingScalper: Multi-Timeframe Institutional Engulfing Scalper for Gold (XAUUSD)

    Quantitative Rationale:
    Retail momentum traders frequently chase 15-minute bullish breakouts and engulfing candles.
    Institutional liquidity providers anticipate this behavior, engineering rapid lower-timeframe
    pullbacks that pierce dynamic volatility bounds (lower ATR band) to sweep late longs' stops.
    When this lower-timeframe sweep encounters aggressive institutional absorption (evidenced by
    elongated lower rejection wicks and surging relative volume), we enter long for an asymmetric
    mean-reverting thrust back toward equilibrium.

    Trade Duration:
    Calibrated for fast intraday scalps lasting between 2 and 10 minutes (averaging 5 minutes,
    max 10 bars), providing multiple high-probability scalping opportunities per trading session.
    """
    INTERFACE_VERSION = 3
    timeframe = '1m'
    can_short = False

    # Risk Management & Dynamic Brackets calibrated for Gold (XAUUSD)
    atr_multiplier = 2.0
    atr_tp_mult = 1.5
    atr_sl_mult = 1.2
    min_wick_ratio = 0.24

    # Holding Windows: Minimum 1 bar, Maximum 10 bars (duration 2 to 10 minutes)
    min_bars = 1
    max_bars = 10

    minimal_roi = {
        "0": 0.005,   # Peak scalp target: +0.50%
        "2": 0.0035,  # After 2 minutes, lock profit if +0.35%
        "6": 0.0015,  # After 6 minutes, lock profit if +0.15%
        "10": 0.0     # Hard 10-minute trade expiration
    }

    stoploss = -0.003  # Baseline hard stop at 0.30%
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Bar Geometry & Wick Physics (Lower Timeframe)
        total_range = (high - low).replace(0, 1e-6)
        dataframe['total_range'] = total_range
        dataframe['body_ratio'] = (close - open_p).abs() / total_range
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / total_range
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / total_range

        # 2. 14-period True Range & Average True Range (ATR)
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # 3. Dynamic Volatility Envelope (Lower Band Piercing Target)
        dataframe['atr_lower_band'] = close.shift(1) - (self.atr_multiplier * dataframe['atr_14'].shift(1))
        dataframe['atr_upper_band'] = close.shift(1) + (self.atr_multiplier * dataframe['atr_14'].shift(1))

        # 4. Volume Z-Score (Effort vs Result)
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std

        # 5. Synthetic 15-Minute Higher Timeframe (HTF) Indicators (15 1m bars = 1 15m candle)
        htf_open = open_p.shift(14).fillna(open_p)
        prev_htf_open = open_p.shift(29).fillna(open_p)
        prev_htf_close = close.shift(15).fillna(close)

        # 15m Bullish Engulfing Structure
        dataframe['htf_bull_engulf'] = (
            (close > htf_open) &
            (prev_htf_close < prev_htf_open) &
            (close >= prev_htf_open)
        ).astype(int)

        # 15m Trend (EMA20 and EMA50: 300 and 750 1m bars)
        dataframe['htf_ema20'] = close.ewm(span=300).mean()
        dataframe['htf_ema50'] = close.ewm(span=750).mean()

        # Active HTF Engulfing Window (signal valid for the 45 minutes following HTF close)
        dataframe['htf_bull_active'] = dataframe['htf_bull_engulf'].rolling(45, min_periods=1).max()

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['enter_long'] = 0
        dataframe['enter_short'] = 0

        long_cond = (
            (dataframe['low'] <= dataframe['atr_lower_band']) &
            (dataframe['lower_wick'] >= self.min_wick_ratio) &
            ((dataframe['close'] > dataframe['htf_ema20']) | (dataframe['htf_bull_active'] == 1) | (dataframe['close'] > dataframe['htf_ema50'])) &
            (dataframe['atr_14'] > 0)
        )
        dataframe.loc[long_cond, 'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe
