# --- Freqtrade / Jesse / EdgeMiner Compatible Strategy Generated by NujinAI ---
# Strategy: XauMtfEngulfingScalper5m (Multi-Timeframe 15m Engulfing & 5m Liquidity Absorption Scalper)
# Asset: XAU/USD (Gold Spot / CFD)
# Timeframe: 5m (with 15m Higher Timeframe Confluence)
# Target Trade Duration: 10 to 50 Minutes (2 to 10 bars on 5m chart)
# Mandatory Prop Firm & Nujin Gates:
#   - Net Sharpe >= 1.80
#   - Max Drawdown <= 4.5%
#   - Win Rate >= 50%
#   - Deflated Sharpe (DSR) >= 0.95
#   - Trade Horizon: min_bars = 1, max_bars = 10

import numpy as np
import pandas as pd
from pandas import DataFrame

try:
    from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
except ImportError:
    class IStrategy:
        pass
    DecimalParameter = float
    IntParameter = int

class XauMtfEngulfingScalper5m(IStrategy):
    """
    XauMtfEngulfingScalper5m: Multi-Timeframe Institutional Engulfing Scalper for Gold (XAUUSD)
    with 5-Minute Confirmation.

    Quantitative Rationale:
    15-minute bullish engulfing structures signal institutional order flow expansion.
    Instead of entering on high-frequency 1-minute microstructure absorptions, this strategy
    waits for a 5-minute candle confirmation:
    1. 5-minute liquidity sweep piercing the dynamic lower volatility bound (lower ATR band).
    2. 5-minute rejection wick showing clear institutional absorption (lower wick >= min_wick_ratio).
    3. Confluence with the active 15-minute bullish engulfing window (valid for 45 minutes / 9 bars)
       or 15-minute trend structure (EMA20/EMA50 on 15m equivalent).

    Trade Duration:
    Holding window spans 1 to 10 5m bars (5 to 50 minutes), capturing larger intraday swings
    than the 1m scalper while filtering out high-frequency 1m noise.
    """
    INTERFACE_VERSION = 3
    timeframe = '5m'
    can_short = False

    # Risk Management & Dynamic Brackets calibrated for Gold (XAUUSD) 5m
    atr_multiplier = 2.0
    atr_tp_mult = 1.5
    atr_sl_mult = 1.2
    min_wick_ratio = 0.24

    # Holding Windows: Minimum 1 bar (5m), Maximum 10 bars (50m)
    min_bars = 1
    max_bars = 10

    minimal_roi = {
        "0": 0.008,
        "2": 0.005,
        "6": 0.0025,
        "10": 0.0
    }

    stoploss = -0.005
    trailing_stop = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        close = dataframe['close']
        open_p = dataframe['open']
        high = dataframe['high']
        low = dataframe['low']
        volume = dataframe['volume']

        # 1. Bar Geometry & Wick Physics (5m Timeframe)
        total_range = (high - low).replace(0, 1e-6)
        dataframe['total_range'] = total_range
        dataframe['body_ratio'] = (close - open_p).abs() / total_range
        dataframe['lower_wick'] = (np.minimum(close, open_p) - low) / total_range
        dataframe['upper_wick'] = (high - np.maximum(close, open_p)) / total_range

        # 2. 14-period True Range & Average True Range (ATR on 5m)
        prev_close = close.shift(1).fillna(open_p)
        tr1 = (high - low).abs()
        tr2 = (high - prev_close).abs()
        tr3 = (low - prev_close).abs()
        dataframe['tr'] = np.maximum(tr1, np.maximum(tr2, tr3))
        dataframe['atr_14'] = dataframe['tr'].rolling(14).mean().fillna(dataframe['tr'])

        # 3. Dynamic Volatility Envelope (Lower Band Piercing Target on 5m)
        dataframe['atr_lower_band'] = close.shift(1) - (self.atr_multiplier * dataframe['atr_14'].shift(1))
        dataframe['atr_upper_band'] = close.shift(1) + (self.atr_multiplier * dataframe['atr_14'].shift(1))

        # 4. Volume Z-Score on 5m
        vol_mean = volume.rolling(20).mean()
        vol_std = volume.rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (volume - vol_mean) / vol_std

        # 5. Synthetic 15-Minute Higher Timeframe (HTF) Indicators (3 5m bars = 1 15m candle)
        htf_open = open_p.shift(2).fillna(open_p)
        prev_htf_open = open_p.shift(5).fillna(open_p)
        prev_htf_close = close.shift(3).fillna(close)

        # 15m Bullish Engulfing Structure
        dataframe['htf_bull_engulf'] = (
            (close > htf_open) &
            (prev_htf_close < prev_htf_open) &
            (close >= prev_htf_open)
        ).astype(int)

        # 15m Trend (EMA20 and EMA50: 20*3 = 60 bars, 50*3 = 150 bars on 5m)
        dataframe['htf_ema20'] = close.ewm(span=60).mean()
        dataframe['htf_ema50'] = close.ewm(span=150).mean()

        # Active HTF Engulfing Window (signal valid for 45 minutes = 9 5m bars)
        dataframe['htf_bull_active'] = dataframe['htf_bull_engulf'].rolling(9, min_periods=1).max()

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['enter_long'] = 0
        dataframe['enter_short'] = 0

        long_cond = (
            (dataframe['low'] <= dataframe['atr_lower_band']) &
            (dataframe['lower_wick'] >= self.min_wick_ratio) &
            ((dataframe['close'] > dataframe['htf_ema20']) | (dataframe['htf_bull_active'] == 1) | (dataframe['close'] > dataframe['htf_ema50'])) &
            (dataframe['atr_14'] > 0)
        )
        dataframe.loc[long_cond, 'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['exit_long'] = 0
        dataframe['exit_short'] = 0
        return dataframe
