#!/usr/bin/env python3
import argparse
import json
import os
import sys

FREQTRADE_TEMPLATE = '''# --- Freqtrade Strategy Generated by NujinSkill Agent ---
# Thesis: {thesis}
# Strategy Framework: Freqtrade (IStrategy)

import numpy as np
import pandas as pd
from pandas import DataFrame
from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter

class {class_name}(IStrategy):
    """
    {thesis}
    Counterparty Trap: Breakout buyers trapped by passive liquidity limit orders.
    """
    INTERFACE_VERSION = 3
    
    # Strategy parameters
    timeframe = '15m'
    can_short = True
    
    # Minimal ROI designed for swing target
    minimal_roi = {{
        "0": 0.04,
        "30": 0.02,
        "60": 0.01
    }}
    
    stoploss = -0.025
    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.015
    
    # Dynamic hyperparameters
    lower_wick_threshold = 0.55
    vol_zscore_threshold = 1.5
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # 1. Total Bar Range
        dataframe['total_range'] = (dataframe['high'] - dataframe['low']).replace(0, 1e-6)
        
        # 2. Wick Geometry
        dataframe['body_ratio'] = (dataframe['close'] - dataframe['open']).abs() / dataframe['total_range']
        dataframe['upper_wick'] = (dataframe['high'] - np.maximum(dataframe['close'], dataframe['open'])) / dataframe['total_range']
        dataframe['lower_wick'] = (np.minimum(dataframe['close'], dataframe['open']) - dataframe['low']) / dataframe['total_range']
        
        # 3. Volume Z-Score (Effort vs Result)
        vol_mean = dataframe['volume'].rolling(20).mean()
        vol_std = dataframe['volume'].rolling(20).std().replace(0, 1e-6)
        dataframe['volume_zscore'] = (dataframe['volume'] - vol_mean) / vol_std
        
        # 4. Rolling Hurst Proxy
        ret1 = np.log(dataframe['close'] / dataframe['close'].shift(1))
        ret5 = np.log(dataframe['close'] / dataframe['close'].shift(5))
        dataframe['hurst_proxy'] = (ret5.rolling(50).var() / (ret1.rolling(50).var().replace(0, 1e-6) * 5.0)).clip(0.1, 0.9)
        
        # 5. Bollinger Bands
        dataframe['sma_20'] = dataframe['close'].rolling(20).mean()
        dataframe['std_20'] = dataframe['close'].rolling(20).std()
        dataframe['upper_band'] = dataframe['sma_20'] + 2.0 * dataframe['std_20']
        dataframe['lower_band'] = dataframe['sma_20'] - 2.0 * dataframe['std_20']
        
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['close'] < dataframe['lower_band']) &
                (dataframe['lower_wick'] > self.lower_wick_threshold) &
                (dataframe['volume_zscore'] > self.vol_zscore_threshold) &
                (dataframe['hurst_proxy'] < 0.48) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'
        ] = 1

        dataframe.loc[
            (
                (dataframe['close'] > dataframe['upper_band']) &
                (dataframe['upper_wick'] > self.lower_wick_threshold) &
                (dataframe['volume_zscore'] > self.vol_zscore_threshold) &
                (dataframe['hurst_proxy'] < 0.48) &
                (dataframe['volume'] > 0)
            ),
            'enter_short'
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['close'] >= dataframe['sma_20'])
            ),
            'exit_long'
        ] = 1

        dataframe.loc[
            (
                (dataframe['close'] <= dataframe['sma_20'])
            ),
            'exit_short'
        ] = 1

        return dataframe
'''

JESSE_TEMPLATE = '''# --- Jesse Strategy Generated by NujinSkill Agent ---
# Thesis: {thesis}

from jesse.strategies import Strategy
import jesse.indicators as ta

class {class_name}(Strategy):
    @property
    def lower_wick(self):
        total_range = max(self.high - self.low, 1e-6)
        return (min(self.close, self.open) - self.low) / total_range

    def should_long(self) -> bool:
        return self.close < self.bb[0] and self.lower_wick > 0.55

    def should_short(self) -> bool:
        return False

    def should_cancel_entry(self) -> bool:
        return True

    def go_long(self):
        qty = 1.0
        self.buy = qty, self.price
        self.stop_loss = qty, self.price * 0.975
        self.take_profit = qty, self.price * 1.04
'''

def emit_strategy(thesis: str, rules_path_or_json: str, framework: str, out_path: str):
    print(f"[StrategyEmitter] Emitting {framework} strategy code for thesis: '{thesis}'...")
    
    # Class name formatting
    clean_thesis = "".join([c for c in thesis.title() if c.isalnum()])
    class_name = f"{clean_thesis}Strategy" if clean_thesis else "NujinSkillStrategy"
    
    if framework.lower() == "jesse":
        code = JESSE_TEMPLATE.format(thesis=thesis, class_name=class_name)
    else:
        code = FREQTRADE_TEMPLATE.format(thesis=thesis, class_name=class_name)
        
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(code.strip() + "\n")
        
    print(f"[StrategyEmitter] Strategy script successfully generated: {out_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Strategy Code Emitter CLI")
    parser.add_argument("--thesis", required=True, help="Economic thesis description")
    parser.add_argument("--rules", default="{}", help="Rules JSON string or path")
    parser.add_argument("--framework", choices=["freqtrade", "jesse"], default="freqtrade", help="Target strategy framework")
    parser.add_argument("--out", required=True, help="Output python strategy file path")
    args = parser.parse_args()
    
    emit_strategy(args.thesis, args.rules, args.framework, args.out)
