#!/usr/bin/env python3
import argparse
import json
import sys
import numpy as np
import pandas as pd

def run_screener(data_path: str, rules_json: str, fee_bps: float, slippage_bps: float, output_path: str):
    print(f"[VectorizedScreener] Loading feature dataset from {data_path}...")
    df = pd.read_csv(data_path)
    
    try:
        rules = json.loads(rules_json) if isinstance(rules_json, str) else rules_json
    except Exception as e:
        print(f"[VectorizedScreener] Error parsing rules JSON: {e}")
        sys.exit(1)
        
    entry_rule = rules.get("entry_long", rules.get("entry", "lower_wick > 0.55 and volume_zscore > 1.5"))
    exit_rule = rules.get("exit", "bars >= 12")
    max_bars = int(rules.get("max_bars_held", 12))

    # Evaluate Entry Conditions safely
    try:
        entries = df.eval(entry_rule).astype(bool)
    except Exception as e:
        print(f"[VectorizedScreener] Failed to evaluate entry rule '{entry_rule}': {e}")
        # Fallback heuristic if string parsing fails
        entries = (df['lower_wick'] > 0.5) & (df['volume_zscore'] > 1.0)

    close_prices = df['close'].values
    n = len(close_prices)
    position = 0
    entry_price = 0.0
    bars_in_trade = 0
    
    total_fee = (fee_bps + slippage_bps) / 10000.0
    trade_returns = []
    daily_returns = np.zeros(n)
    
    for i in range(1, n):
        if position == 0:
            if entries.iloc[i-1]:
                position = 1
                entry_price = close_prices[i] * (1.0 + total_fee) # Buy with slippage & fee
                bars_in_trade = 0
        elif position == 1:
            bars_in_trade += 1
            current_price = close_prices[i]
            # Simple bar holding exit or target/stop exit
            if bars_in_trade >= max_bars or i == n - 1:
                exit_price = current_price * (1.0 - total_fee) # Sell with fee
                ret = (exit_price - entry_price) / entry_price
                trade_returns.append(ret)
                daily_returns[i] = ret
                position = 0

    trade_returns = np.array(trade_returns)
    num_trades = len(trade_returns)
    
    if num_trades == 0:
        results = {
            "status": "REJECT",
            "reason": "Zero trades generated by strategy rules",
            "sharpe": 0.0,
            "trades": 0,
            "win_rate": 0.0,
            "profit_factor": 0.0,
            "max_drawdown": 0.0,
            "expectancy_bps": 0.0
        }
        print(json.dumps(results, indent=2))
        with open(output_path, 'w') as f:
            json.dump([], f)
        return

    wins = trade_returns[trade_returns > 0]
    losses = trade_returns[trade_returns < 0]
    win_rate = float(len(wins) / num_trades) if num_trades > 0 else 0.0
    gross_profit = float(np.sum(wins)) if len(wins) > 0 else 0.0
    gross_loss = float(np.abs(np.sum(losses))) if len(losses) > 0 else 1e-6
    profit_factor = gross_profit / gross_loss
    
    mean_ret = float(np.mean(trade_returns))
    std_ret = float(np.std(trade_returns, ddof=1)) if num_trades > 1 else 1.0
    sharpe = float((mean_ret / std_ret) * np.sqrt(252)) if std_ret > 0 else 0.0
    
    cum_returns = np.cumsum(trade_returns)
    peak = np.maximum.accumulate(cum_returns)
    drawdowns = (peak - cum_returns)
    max_dd = float(np.max(drawdowns)) if len(drawdowns) > 0 else 0.0
    
    expectancy_bps = mean_ret * 10000.0
    fee_threshold_bps = 2.0 * (fee_bps + slippage_bps)
    
    # Automated Rejection Hurdles
    reasons = []
    if sharpe < 1.3:
        reasons.append(f"Sharpe {sharpe:.2f} < 1.3")
    if num_trades < 100:
        reasons.append(f"Trades {num_trades} < 100")
    if profit_factor < 1.4:
        reasons.append(f"Profit Factor {profit_factor:.2f} < 1.4")
    if expectancy_bps <= fee_threshold_bps:
        reasons.append(f"Expectancy {expectancy_bps:.1f}bps <= 2x Fees ({fee_threshold_bps:.1f}bps)")
        
    status = "PASS" if len(reasons) == 0 else "REJECT"
    
    summary = {
        "status": status,
        "reasons": reasons,
        "sharpe": round(sharpe, 4),
        "trades": num_trades,
        "win_rate": round(win_rate, 4),
        "profit_factor": round(profit_factor, 4),
        "max_drawdown": round(max_dd, 4),
        "expectancy_bps": round(expectancy_bps, 2),
        "fee_bps": fee_bps,
        "slippage_bps": slippage_bps
    }
    
    print(json.dumps(summary, indent=2))
    
    # Save detailed return series for Phase 4 validation
    with open(output_path, 'w') as f:
        json.dump(trade_returns.tolist(), f)
    print(f"[VectorizedScreener] Candidate trade returns written to {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Vectorized In-Sample Strategy Coarse Filter")
    parser.add_argument("--data", required=True, help="Input features CSV file path")
    parser.add_argument("--rules", required=True, help="Rule dict or JSON string specifying strategy entry/exit")
    parser.add_argument("--fee-bps", type=float, default=5.0, help="Taker fee in bps (default: 5.0)")
    parser.add_argument("--slippage-bps", type=float, default=2.0, help="Slippage in bps (default: 2.0)")
    parser.add_argument("--output", required=True, help="Output JSON path for trade return series")
    args = parser.parse_args()
    
    run_screener(args.data, args.rules, args.fee_bps, args.slippage_bps, args.output)
